kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc-2
spec:
  storageClassName: "standard" # Static provisioning
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
