kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc
spec:
  storageClassName: "" # Static provisioning
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
