apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-hello-world
  labels:
    track: canary
spec:
  selector:
    matchLabels:
      run: pod-hello-world
  template:
    metadata:
      labels:
        run: pod-hello-world
    spec:
      containers:
      - name: cont1
        image: learnk8s/app:1.0.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-hello-world
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    run: pod-hello-world
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-hello-world
spec:
  rules:
  - http:
      paths:
      - path: "/"
        backend:
          serviceName: service-hello-world
          servicePort: 80


