apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  labels:
    app: httpd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - image: httpd
          name: httpd
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/usr/local/apache2/htdocs"
              name: hostpath-vol
      volumes:
        - name: hostpath-vol
          persistentVolumeClaim:
            claimName: hostpath-pvc
