kind: PersistentVolume
apiVersion: v1
metadata:
  name: hostpath-vol
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/docker/app/sharedfolder"