apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
  - name: mysql
    image: mysql:5.7
    readinessProbe:
      exec:
        command: ["mysql", "-h", "127.0.0.1", "-e", "SELECT 1"]
      # If you know that the application isn't ready, 
      # and it doesn't make sense to probe, you can
      # set an initial delay.
      initialDelaySeconds: 5
      # After the initial delay, the probe checks the container 
      # at regular intervals (defaults to 10 seconds).
      periodSeconds: 2
      timeoutSeconds: 1
